# Generated by Django 3.0.3 on 2020-03-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
                ('description', models.CharField(max_length=140)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
        ),
    ]
