# Generated by Django 3.0.3 on 2020-03-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydjango', '0002_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='goods',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
