# Generated by Django 3.0.3 on 2020-02-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
                ('comment', models.CharField(max_length=140)),
                ('regi_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
