# Generated by Django 3.0.3 on 2020-02-13 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200213_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='regi_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
